longhorn/longhorn-instance-manager

vendor.conf, vendor/github.com/rancher/go-iscsi-helper/iscsi/target.go
To fix engine integration test issue
=> Update vendor for go-iscsi-helper

engine/engine_manager.go, process/process_manager.go
This PR implements a fix for a possible deadlock that could occur if there were a significant number of updates that were being sent while the `Manager` was trying to clean up a dead `Watch`. Previously, if a lot of updates were being sent over `Watch`, there would be conflict over trying to get ahold of the `Lock` for the `Manager`. If a `Watch` was trying to be removed, it would break the `for loop` responsible for handling these updates, so messages sent over the `channel` would never be retrieved and never release the `Lock` needed for the `Manager` to stop the `Watch`, resulting in the deadlock.
Now, each `Watch` is stored with a corresponding `stopCh`, which allows for the update handler to check if the `Watch` is no longer handling new messages over the channel, dropping the update …
=> Fix deadlock on flood of Engine/Process updates

process/process.go, process/process_test.go
And add test cases for the process states
=> process: Restore stop to be an async process

.drone.yml
=> build: Add automatic build failure notification to slack

Dockerfile.dapper, pkg/process/process.go, pkg/process/process_manager.go, pkg/process/process_test.go, pkg/util/util.go
https://github.com/longhorn/longhorn/issues/1113
=> process: Fix race condition caused by repeated calls for ProcessDelete

pkg/process/process.go
=> Fix the deadlock caused by the invalid binary path not found during the process creation

pkg/process/healthchecker.go
https://github.com/longhorn/longhorn/issues/1854
Signed-off-by: Bo Tao <bo.tao@rancher.com>
=> Fix ticker leaking in HealthChecker 'WaitForRunning' function.

.drone.yml, Dockerfile.dapper, package/Dockerfile, scripts/package
https://github.com/longhorn/longhorn/issues/6
=> 6 arm support for instance manager

.drone.yml
https://github.com/longhorn/longhorn/issues/6
Signed-off-by: Bo Tao <bo.tao@rancher.com>
=> Update drone base docker image to ubuntu18.04

.drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
=> add drone slack notifications

.gitignore, go.mod, go.sum, package/Dockerfile, vendor/github.com/satori/go.uuid/.travis.yml, vendor/github.com/satori/go.uuid/LICENSE, vendor/github.com/satori/go.uuid/README.md, vendor/github.com/satori/go.uuid/codec.go, vendor/github.com/satori/go.uuid/generator.go, vendor/github.com/satori/go.uuid/sql.go, vendor/github.com/satori/go.uuid/uuid.go, vendor/modules.txt
Signed-off-by: David Ko <dko@suse.com>
ref: https://github.com/longhorn/longhorn/issues/2763
=> Frequently update packages when building image

Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/2206
Signed-off-by: Keith Lucas <keith.lucas@suse.com>
=> Update liblonghorn version

.drone.yml, Dockerfile.dapper, scripts/package
This PR adds support to build on s390x architecture.
=> Add s390x support

app/cmd/process.go, app/cmd/start.go, app/cmd/version.go, main.go, pkg/api/types.go, pkg/client/process_manager.go, pkg/util/grpcutil.go
Tracking issue longhorn/longhorn#3839
=> MTLS authentication implementation

app/cmd/start.go
Signed-off-by: David Ko <dko@suse.com>
https://github.com/longhorn/longhorn/issues/3922
=> Fallback to non-tls connection if tls files not found

pkg/client/proxy.go, pkg/client/proxy_backup.go, pkg/client/proxy_replica.go, pkg/client/proxy_snapshot.go, pkg/client/proxy_volume.go
https://github.com/longhorn/longhorn/issues/4008
https://github.com/longhorn/longhorn/issues/3546
=> grpc-proxy: cleanup intermediate client logging

pkg/client/proxy.go
https://github.com/longhorn/longhorn/issues/3967
=> grpc-proxy: add client keepalive

pkg/client/proxy.go, pkg/client/proxy_backup.go, pkg/client/proxy_replica.go, pkg/client/proxy_snapshot.go, pkg/client/proxy_volume.go
https://github.com/longhorn/longhorn/issues/4060
=> grpc-proxy: use ctx w/timeout for gRPC proxy client

pkg/client/proxy_backup.go
[Longhorn 4049](https://github.com/longhorn/longhorn/issues/4049)
=> Fix incorrect error returned of BackupRestore()

Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/4059
Signed-off-by: Keith Lucas <keith.lucas@suse.com>
=> Update liblonghorn version for little-endian fix

pkg/client/proxy.go, pkg/client/proxy_replica.go, pkg/client/proxy_snapshot.go
https://github.com/longhorn/longhorn/issues/4096
=> grpc-proxy: use long timeout for proxy clients

pkg/client/proxy.go
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
=> grpc-proxy: adjust log level

pkg/client/proxy_snapshot.go
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
=> refactor: misleading VolumeSnapshot argument

Dockerfile.dapper, package/Dockerfile
Depends on https://github.com/rancher/tgt/pull/8 and https://github.com/rancher/liblonghorn/pull/16
[Longhorn 4136](https://github.com/longhorn/longhorn/issues/4136)
=> Add tcmalloc for amd64 platform

pkg/client/proxy_backup.go
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
=> fix: none-json error from backup store

go.mod, go.sum, vendor/github.com/longhorn/longhorn-engine/pkg/replica/replica.go, vendor/github.com/longhorn/longhorn-engine/pkg/sync/sync.go, vendor/modules.txt
=> vendor: Update longhorn/longhorn-engine

go.mod, go.sum, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
[Longhorn 4552](https://github.com/longhorn/longhorn/issues/4552)
=> vendor: update backupstore

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/util/util.go, vendor/modules.txt
longhorn/longhorn#4552
longhorn/longhorn#4580
=> vendor: update longhorn-engine

pkg/client/proxy.go, pkg/proxy/backup.go, pkg/proxy/proxy.go, pkg/proxy/replica.go, pkg/proxy/snapshot.go, pkg/proxy/volume.go
[Longhorn 4427
](https://github.com/longhorn/longhorn/issues/4427)
=> Change some log messages to trace level

Dockerfile.dapper, package/Dockerfile
=> Update tgt for online expansion

app/cmd/process.go, app/cmd/start.go, app/cmd/version.go, pkg/client/process_manager.go, pkg/client/proxy_replica.go, pkg/health/health_probe.go, pkg/process/healthchecker.go, pkg/process/process.go, pkg/process/process_manager.go, pkg/proxy/backup.go, pkg/proxy/healthchecker.go, pkg/proxy/proxy.go, pkg/proxy/replica.go, pkg/proxy/snapshot.go, pkg/proxy/volume.go, pkg/util/util.go
=> Change some debug level message to info level

Dockerfile.dapper, package/Dockerfile
=> package: update tcmalloc to 2.10

Dockerfile.dapper, package/Dockerfile
Longhorn/longhorn#5050
Longhorn/longhorn#5051
=> [BACKPORT][v1.3.3] package: update tcmalloc to 2.10

Dockerfile.dapper, package/Dockerfile
=> [BACKPORT][v1.4.x] package: update tcmalloc to 2.10

Dockerfile.dapper, package/Dockerfile
=> Disable tcmalloc

Dockerfile.dapper, package/Dockerfile
=> [BACKPORT][v1.4.0] Disable tcmalloc

Dockerfile.dapper, package/Dockerfile
Longhorn/longhorn#5096
https://github.com/longhorn/longhorn/issues/5097
=> [BACKPORT][v1.3.3] Disable tcmalloc

go.mod, go.sum, vendor/github.com/longhorn/backupstore/Dockerfile.dapper, vendor/github.com/longhorn/backupstore/backupstore.go, vendor/github.com/longhorn/backupstore/config.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/fsops/fsops.go, vendor/github.com/longhorn/backupstore/go.mod, vendor/github.com/longhorn/backupstore/http/client.go, vendor/github.com/longhorn/backupstore/list.go, vendor/github.com/longhorn/backupstore/lock.go, vendor/github.com/longhorn/backupstore/logging/logging.go, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/s3/s3.go, vendor/github.com/longhorn/backupstore/s3/s3_service.go, vendor/github.com/longhorn/backupstore/singlefile.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/github.com/longhorn/backupstore/vfs/vfs.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/modules.txt
from `20220913112826-5f5c95274f2a` to ~`20230316055339-4879228b1209`~ `20230306022849-8d5e216c3b33`
longhorn/longhorn#5265
Regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3313/
=> vendor: update `backupstore` by v1.3.x branch

package/Dockerfile, package/engine-manager, package/instance-manager, pkg/meta/version.go
https://github.com/longhorn/longhorn/issues/5208
=> feat: consolidate instance managers

go.mod, go.sum, vendor/modules.txt
ref: https://github.com/longhorn/longhorn/issues/5656
=> vandor: update engine

package/Dockerfile, scripts/package
Reduce image size from 444 MiB to 268 MiB
Longhorn/longhorn#6022
=> build: minimize docker mage using multistage multi-stage builds

package/Dockerfile
=> build: add go-spdk-helper for debugging and troubleshooting

go.mod, go.sum, vendor/github.com/longhorn/go-spdk-helper/pkg/jsonrpc/client.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go, vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/modules.txt
=> vendor: update go-spdk-helper and longhorn-spdk-engine

go.mod, go.sum, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/nvme.go, vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/client.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go, vendor/modules.txt
Waiting for https://github.com/longhorn/longhorn-spdk-engine/pull/52
Longhorn/longhorn#6110
=> vendor: update longhorn-spdk-engine

go.mod, go.sum, pkg/client/disk.go, pkg/disk/disk.go, vendor/github.com/longhorn/go-spdk-helper/pkg/jsonrpc/client.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/util/http_util.go, vendor/modules.txt
backport of pull request https://github.com/longhorn/longhorn-instance-manager/pull/258
=> Update SPDK repos and improve logs (backport #258)

go.mod, go.sum, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go, vendor/modules.txt
=> vendor: update go-spdk-helper

go.mod, go.sum, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go, vendor/modules.txt
=> [v1.5.x]vendor: update go-spdk-helper

go.mod, go.sum, package/Dockerfile, package/instance-manager, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/bdev.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go, vendor/modules.txt
=> Use nvme cli in container instead

go.mod, go.sum, package/Dockerfile, package/instance-manager, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/bdev.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/client/client.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/6798
https://github.com/longhorn/longhorn/issues/6828
=> [BACKPORT][v1.5.2] Use nvme cli in container instead

main.go, pkg/util/log.go
ref: https://github.com/longhorn/longhorn/issues/5509
=> feat(log): add function name and line number in log message

app/cmd/start.go
Many workloads such as v2 volume backup are executed inside the instance-manager process. To profile the cpu and memory consumptions of the workloads, we can create a pprof server in the instance-manager pod.
Longhorn/longhorn#6377
=> Add pprof server in instance-manager pod

Dockerfile.dapper
ref: https://github.com/longhorn/longhorn/issues/5911
=> build: remove unecessary build steps

go.mod, go.sum, package/Dockerfile, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/bdev.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go, vendor/modules.txt
https://github.com/longhorn/security/issues/16
=> fix: CVE issues

package/Dockerfile, scripts/package
ref: https://github.com/longhorn/longhorn/issues/5911
This is the manual PR to update v1.4.x Dockerfile
=> [Backport 1.4.x ] build: reduce iamge size by introducing multi stage build

package/Dockerfile
ref: https://github.com/longhorn/longhorn/issues/5911
=> build: add xfs tool back

pkg/client/proxy.go, pkg/util/grpcutil.go
https://github.com/longhorn/longhorn/issues/7291
=> refactor: replace deprecated grpc.WithInsecure

Dockerfile.dapper, pkg/util/grpcutil.go
longhorn/longhorn#7341
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5387/
=> Build with Go v1.21

package/Dockerfile, package/instance-manager
longhorn/longhorn#7190
deps on https://github.com/longhorn/go-spdk-helper/pull/60
=> nvme: create a pair of hostid and hostnqn

package/Dockerfile
=> v2 volume: support arm64 platform

proto/vendor/github.com/longhorn/longhorn-engine/proto/ptypes/common.proto, proto/vendor/github.com/longhorn/longhorn-engine/proto/ptypes/controller.proto, proto/vendor/github.com/longhorn/longhorn-engine/proto/ptypes/syncagent.proto
https://github.com/longhorn/longhorn/issues/6666
=> feat: sync latest proto from longhorn-engine

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/modules.txt
=> vendor: update dependencies

go.mod, go.sum, package/Dockerfile, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go, vendor/modules.txt
Issue longhorn/longhorn#7551
1. Add netcat package which is used for probing the liveness of grpc services.
2. Update dependencies
=> Add netcat package and update dependencies

pkg/proxy/proxy.go, pkg/proxy/volume.go
Issue Longhorn/longhorn#7555
Add newly introduced methods `VolumeSnapshotMaxCountSet` and `VolumeSnapshotMaxSizeSet`.
=> proxy: update ProxyOps

pkg/meta/version.go
https://github.com/longhorn/longhorn/issues/7555
=> feat: bump InstanceManagerAPIVersion to 5

package/Dockerfile
https://github.com/longhorn/longhorn/issues/7523
=> fix(cve): update dependencies

pkg/client/proxy_volume.go
https://github.com/longhorn/longhorn/issues/6563
In https://github.com/longhorn/longhorn-instance-manager/pull/348, we replaced backend store driver with data engine. We should also apply it on snapshot related APIs.
=> fix: replace backend store driver with data engine

app/cmd/start.go
No need to error out.
Issue Longhorn/longhorn#7608
Just make the best effort to clean up stale NVMe and device mapper devices.
=> Make the best effort to clean up stale NVMe and device mapper devices

package/Dockerfile
Issue https://github.com/longhorn/longhorn/issues/7609
=> Dockerfile: update nvme-cli to v2.7.1

app/cmd/start.go, go.mod, go.sum, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go, vendor/modules.txt
Issue longhorn/longhorn#7615
Do not use --force for dmsetup remove command for avoiding the potential stuck process.
=> Do not use --force for dmsetup remove command

pkg/proxy/snapshot.go
Issue longhorn/longhorn#7622
proxy: add volume-head to snapshot list
=> proxy: add volume-head to snapshot list

app/cmd/start.go, pkg/instance/instance.go, pkg/proxy/backup.go, pkg/proxy/replica.go, pkg/proxy/snapshot.go, pkg/proxy/volume.go
Issue longhorn/longhorn#7628
Refactor instance gRPC methods and make them easy to maintain.
=> Refactor instance gRPC methods

pkg/disk/disk.go
Issue https://github.com/longhorn/longhorn/issues/7628
=> Refactor disk gRPC methods

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/modules.txt
=> vendor: Update longhorn/longhorn-spdk-engine

app/cmd/process.go, app/cmd/version.go, pkg/client/disk.go, pkg/client/instance.go, pkg/client/process_manager.go, pkg/instance/instance.go
=> grpc: add checkConnection for process manager, instance and disk services

.drone.yml
ref: longhorn/longhorn#8166
Signed-off-by: davidko <dko@suse.com>
=> ci: rollback BCI image to 15.5

package/Dockerfile
Issue https://github.com/longhorn/longhorn/issues/8187
We forgot to update the SPDK commit ID for instance manager after doing that in longhorn/longhorn-spdk-engine
=> Dockerfile: Update SPDK commit ID

pkg/process/process.go
=> chore: Fix comment

Dockerfile.dapper, scripts/ci, scripts/generate-grpc
We can remove this when https://github.com/FrankYang0529/longhorn-interface is introduced officially. The code in this PR is similar to that of longhorn-engine.
=> Add gRPC validation

package/Dockerfile
=> Dockerfile: update spdk to eabc229

package/Dockerfile
=> Dockerfile: update spdk to 62a8f8a

app/cmd/start.go, pkg/api/instance.go, pkg/disk/disk.go, pkg/instance/instance.go, pkg/process/command.go, pkg/process/process_test.go, pkg/proxy/proxy.go, pkg/util/grpcutil.go, pkg/util/log.go, scripts/validate
https://github.com/longhorn/longhorn/issues/7448
=> fix: golangci-lint error

Dockerfile.dapper, package/Dockerfile
=> Dockerfile: update golang to 1.22.2

pkg/disk/disk.go, pkg/instance/instance.go, pkg/proxy/proxy.go
=> Fix high CPU usage of instance-manager pod caused by for loop

.github/workflows/build.yml
https://github.com/longhorn/longhorn/issues/8039
=> ci: change oracle-aarch64-4cpu-16gb to longhorn-infra-arm64-runners

pkg/util/grpcutil.go
=> Remove deprecated grpc.Dial use, replace with grpc.NewClient

.gitignore
=> .gitignore: exclude Dockerfile.dapper[0-9]*

package/Dockerfile
=> chore(nvme): update nvme-cli to v2.9.1

package/Dockerfile
=> chore(dockerfile): fix the dependencies of spdk_tgt missing caused by bci-base:15.6

package/Dockerfile
=> chore(dockerfile): update go-spdk-helper to 99b2a18

go.mod, go.sum, package/Dockerfile, vendor/modules.txt
=> chore(dockerfile): update go-spdk-helper and spdk

go.mod, go.sum, pkg/proxy/snapshot.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/modules.txt
=> fix(snapshot): fix missing userCreated in SnapshotList()

go.mod, go.sum, package/Dockerfile, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/modules.txt
Set user_created to true when the xattr isn´t available to let the UI to show the snapshots list.
Issue #9054
=> fix(deps): update dependencies for user_created fallback

go.mod, go.sum, pkg/client/disk.go, pkg/disk/disk.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/client/client.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/disk.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/disk/nvme/nvme.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/disk/virtio-blk/virtio-blk.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/disk/virtio-scsi/virtio-scsi.go, vendor/modules.txt
=> fix(disk): no need to check disk UUID while deleting a disk

go.mod, go.sum, vendor/modules.txt
=> chore(vendor): update dependencies

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/util.go, vendor/modules.txt
Longhorn/longhorn#7199 
Longhorn/longhorn#9121
Issue #
=> fix: update vendor longhorn/longhorn-spdk-engine for SPDK online rebuilding bug

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/types.go, vendor/modules.txt
Issue longhorn/longhorn#7199, longhorn/longhorn#9121
=> fix: update vendor longhorn/longhorn-spdk-engine for SPDK online rebuilding

package/instance-manager
=> feat(v2 volume/configurable cpu mask): support configurable CPU cores

package/Dockerfile
Issue longhorn/longhorn#8722, longhorn/longhorn#8721
Refresh and update release image system packages.
- TODO: backport to master and v1.7.x.
`None`
=> build(image): always update system packages

pkg/disk/disk.go, pkg/instance/instance.go, pkg/proxy/proxy.go
longhorn/longhorn#9438
Fixing a nit. We don't need the for loop
=> nit(refactor): remove the unnecessary for loop

package/Dockerfile
Issue longhorn/longhorn#9714
Install the latest grpc_health_probe at build time.
`None`
`None`
=> build: install latest grpc_health_probe

app/cmd/start.go, pkg/proxy/backup.go, pkg/proxy/replica.go, pkg/proxy/snapshot.go
=> fix: fix "printf: non-constant format string in call...."

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/modules.txt
Issue longhorn/longhorn#9852
Update vendor.
`None`
`None`
=> chore: update vendor

go.mod, go.sum, pkg/instance/instance.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go, vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/advanced.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go, vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go, vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/client/client.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go, vendor/modules.txt
Signed-off-by: Derek Su <derek.su@suse.com>#### Which issue(s) this PR fixes:
Issue Longhorn/longhorn#9199
=> feat(proxy): remove UpgradeRequested parameter from EngineCreate()

package/instance-manager
=> fix: no need to start tgtd in an instance-manager pod for v2 data engine

package/Dockerfile
Longhorn 5573
https://github.com/longhorn/longhorn/issues/5573
=> fix: update go_spdk_helper commit ID for dapper file

.github/workflows/build.yml
=> chore(workflow): update arm64 runner to longhorn-infra-oracle-arm64-runners

go.mod, go.sum, vendor/golang.org/x/net/http2/config.go, vendor/golang.org/x/net/http2/config_go124.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/sys/unix/syscall_dragonfly.go, vendor/golang.org/x/sys/windows/dll_windows.go, vendor/modules.txt
Issue longhorn/longhorn#9897
Fix CVE issues.
`None`
`None`
=> chore(cve): update dependencies

.github/workflows/build.yml
=> chore(build): use oracle cloud runner

pkg/proxy/replica.go
=> fix: proxy remove tcp prefix for v2 replica remove

pkg/proxy/replica.go
Issue https://github.com/longhorn/longhorn/issues/10347
=> fix: proxy add tcp prefix for v2 engine API ReplicaList returning address

package/Dockerfile, scripts/package
=> chore(build): support tag in longhorn/dep-versions

.github/workflows/build.yml, Dockerfile.dapper, Makefile, scripts/package
Supports security build.
Prepare for potential secure release
The secrets provided by EIO MUST NOT present in any visible output.
Guidance on achieving SLSA Level 3
=> feat: new makefile target for secure image build

.github/workflows/build.yml, package/Dockerfile, scripts/package
=> fix(ci): fix binary dependency for local image packaging

.github/workflows/build.yml, Dockerfile.dapper, Makefile, package/Dockerfile, scripts/package
Backport the following secure PRs to v1.8.x:
- #853 
- #884 
- #885
=> feat(ci): Backport secure build to v1.8.x

go.mod, go.sum, vendor/github.com/longhorn/longhorn-engine/pkg/replica/client/client.go, vendor/github.com/longhorn/longhorn-engine/pkg/replica/replica.go, vendor/github.com/longhorn/longhorn-engine/pkg/types/resource.go, vendor/github.com/longhorn/longhorn-engine/pkg/types/types.go, vendor/modules.txt
=> [BACKPORT][v1.8.1] chore(vendor): update dependencies

package/Dockerfile
Issue `None`
Fix build failure:
```
Problem accessing the file at the specified URI:
File '/repositories/devel:languages:python:backports/SLE_15/devel:languages:python:backports.repo' not found on medium 'https://download.opensuse.org/'
```
`None`
`None`
=> fix(build): devel:languages:python:backports.repo not found on medium 

package/Dockerfile
Issue https://github.com/longhorn/longhorn/issues/10653
=> fix: dockerfile misses some deps in /usr/lib64

app/cmd/process.go, app/cmd/version.go, package/Dockerfile, pkg/health/health_probe.go, pkg/instance/instance.go, pkg/instance/log.go, pkg/proxy/backing_image.go, pkg/proxy/backup.go, pkg/proxy/metrics.go, pkg/proxy/proxy.go, pkg/proxy/replica.go, pkg/proxy/snapshot.go, pkg/proxy/volume.go, pkg/util/log.go, pkg/util/util.go
=> fix: fix validation errors

Dockerfile.dapper, go.mod, go.sum, package/Dockerfile, vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/initiator.go, vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/nvme.go, vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/nvmecli.go, vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/ublk_id_generator.go, vendor/github.com/longhorn/go-spdk-helper/pkg/jsonrpc/types.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/ublk.go, vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/ublk.go, vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go, vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/backing_image.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/backup.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/restore.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/util.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/types/types.go, vendor/modules.txt
in-progress
longhorn/longhorn#9456
=> feat: implement ublk frontend for v2 data engine

go.mod, go.sum, pkg/proxy/replica.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/types.go, vendor/modules.txt
Issue https://github.com/longhorn/longhorn/issues/10563
=> feat: stop checksum hash

package/Dockerfile
See more details https://github.com/longhorn/longhorn/issues/10768#issuecomment-2825685800
longhorn/longhorn#10768
=> fix: specify gcc13 for SPDK building

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go, vendor/modules.txt
Issue longhorn/longhorn#10798 longhorn/longhorn#10563
=> fix: update vendor for v2 snapshot hash bugs

Dockerfile.dapper
=> chore(dockerfile): move libqcow to dedicated GitHub repo (longhorn/libqcow)

package/Dockerfile
=> fix: outdated SLES repo

package/instance-manager
Issue longhorn/longhorn#9834, ~longhorn/longhorn#9419~
Support interrupt mode for V2 volumes.
=> feat(v2): support interrupt mode

go.mod, go.sum, vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/11767
update longhorn-spdk-engine
=> chore(deps): update go.mod and vendor
