- engine.go
- launcher.go
We may hit `connection refused` if we connect too soon.
> Add wait period for the new rest server

- launcher.go
Leftover from previous run shouldn't cause such a fatal failure
> launcher: Automatically clean up the existing same name device

- api/types.go
- client/engine_manager.go
- client/process_manager.go
This PR fixes the `gRPC client` implementation of `LogStream` on both `EngineManagerClient` and `ProcessManagerClient` to avoid automatically closing the `Connection` or cancelling the `Context`, leaving it up to the `Client` to manually call the `Close()` method instead. This allows the `Stream` to actually be functional instead of immediately being closed right after its creation.
> Don't prematurely close connection for LogStreams

- process/process_manager.go
This PR fixes a possible deadlock that could occur in the situation of a large surge in `Processes` attempting to be unregistered by the `Instance Manager`. In this situation, the `Process Manager` would attempt to send an update to the `updateCh` before releasing the `Process Manager` lock. However, if a large number of `Processes` attempted this at the same time, another `Process` could hold the lock required for the `updateCh` to finish processing the previous update, causing a deadlock.
The `Process Manager` now immediately releases the `Process Manager` lock once it has been unregistered so that other processes may proceed with doing the same and so the `updateCh` can have a chance at attaining the `Process Manager` lock to continue processing the `Watch` update.
> Fix deadlock on surge in Process removals

- engine/engine_manager.go
- process/process_manager.go
- process/process_test.go
Detected by the process unit test with only two concurrent threads.
Now we can bump up the thread number to 100 for the basic unit test.
Also fix a similar issue of the engine.
> process/engine: Fix the deadlock while sending response to channel

- app/start.go
- engine/engine_manager.go
Since engines use processes. Otherwise the shutdown process will stuck
for 30s since engines failed to find correlated processes.
Also fixes a typo.
> app: cleanup shuts down engines first

- engine/engine_launcher.go
- engine/engine_manager.go
- process/process_manager.go
Engine manager now maintains a list for the engineName to launcher map.
Previous implementation results only one of the launcher will receive
the notification, as well as left launcher monitoring thread behind.
> engine: Remove per launcher monitor

- process/process.go
> process: Remove the happy path debug message for process update

- Dockerfile.dapper
- package/Dockerfile
- package/engine-manager
- scripts/ci
- scripts/package
Also build tgtd in the instance manager image because it's the running
environment for the engine.
> build: add package for building docker image

- Dockerfile.dapper
- scripts/package
To make it separate from the engine image version.
It looks like: `longhornio/longhorn-instance-manager:v1_20200301`
> package: Set the instance manager image tag to API Version + date

- pkg/util/util.go
Hi,
Another small MR to make `GetURL` IPv6 ready for IPv6-only cluster. This function is actually used by the `longhorn-manager` code
Once this MR is merged, I'll be able to make another one in longhorn-manager (https://github.com/Frankkkkk/longhorn-manager/commit/aaec3d48717247e8b28e1e2a51f9aa313f5122ee , still WIP)
Related to https://github.com/longhorn/longhorn-manager/pull/663 and https://github.com/longhorn/longhorn-ui/pull/320
Cheers !
> 🐛 Utils: make GetURL IPv6 ready

- .gitignore
- pkg/process/command.go
- pkg/process/process.go
- pkg/process/process_manager.go
- pkg/process/process_test.go
data race / deadlock fix
there was a race in the process UpdateChannel assignment
the above race leads to a deadlock when the binary couldn't be located.
nil pointer fix:
there was a nil pointer case, while updating a process that is being
deleted, since when initially checked the process was still in the map
but by the time new process has started the old process had been removed
final deadlock which could be triggered through concurrent calls
while trying todo process replacement, explanation for this deadlock is below, 
this one could be quite common during parallel engine upgrades for example:
// there was a deadlock when the im.monitor is processing an element
// from the updateChannel, it will try to RLock, to evaluate the existing
// processes. This will deadlock, if during that …
> Fixes issues surrounding process replacement

- pkg/client/process_manager.go
- the VersionGet grpc connection is always leaked
- the streaming grpc connections are leaked in the call error case
I saw this and decided to fix it quickly while I was looking into something else.
longhorn/longhorn#2824
> Fix grpc client connection leak (VersionGet, ProcessLog, ProcessWatch)

- Dockerfile.dapper
- package/Dockerfile
Update liblonghorn to use little endian for communication.
This is required for s390x compatibility.
> Update liblonghorn version

- .drone.yml
Adding missing `s390x` arch for HEAD images
Signed-off-by: Luis Tovar <luis.tovar@suse.coM>
> Adding s390x arch for HEAD images

- app/cmd/process.go
- app/cmd/start.go
- main.go
- pkg/util/grpcutil.go
- pkg/util/grpcutil_test.go
- fixed the cli client non tls fallback
- added cli tcp:// to the default endpoint (listen/url)
- fallback to tcp in case endpoint doesn't specify proto (client/server)
- added unit tests for parseEndpoint function
longhorn/longhorn#3966
> fix cli im client non tls fallback

- pkg/meta/version.go
InstanceManager APIs are not updated, so revert the InstanceManagerAPIVersion update.
longhorn/longhorn#4210
longhorn/longhorn#3198
> meta: revert InstanceManagerAPIVersion update

- pkg/meta/version.go
To distinguish if the instance manager supports online expansion, we have to bump up the API version
Longhorn/longhorn#1674
> meta: Bump up the API version by 1

- pkg/process/process_manager.go
The only usecase of ProcessReplace is for engine image live upgrade. If the new engine process has the same binary as the existing engine process, there is no reason to do the ProcessReplace
longhorn/longhorn#5684
> Fix bug: volume is stuck in live engine upgrading

- go.mod
- go.sum
- pkg/instance/instance.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/client/client.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go
- vendor/modules.txt
During instance watching, errors can happen due to gRPC server and client errors or keepalive errors. Whenever the error count reaches a maximum, error out the instance watch function.
Longhorn/longhorn#6578
> Error out when continuously receiving errors while watching instances

- pkg/process/process_manager.go
The function ProcessReplace() doesn't initialize the Conditions map which causes the panic "assignment to entry in nil map" when getProcessToUpdateConditions() attempts to add a key to it
We can observe this error log right after the ProcessReplace() finished:
```
[longhorn-instance-manager] time="2024-01-04T06:35:28Z" level=info msg="Process Manager: successfully replaced process longhorn-testvol-jogcok-e-0" func="process.(*Manager).ProcessReplace" file="process_manager.go:583"
[longhorn-instance-manager] time="2024-01-04T06:35:28Z" level=info msg="Process Manager: successfully unregistered process longhorn-testvol-jogcok-r-9b014111" func="process.(*Manager).unregisterProcess.func1" file="process_manager.go:343"
panic: assignment to entry in nil map
goroutine 14 [running]: …
```
> Fix bug instance manager pod crashed after upgrading engine image

- pkg/process/process_manager.go
longhorn/longhorn#7919
There is a potential deadlock caused by `pm.getProcessesToUpdateConditions`. See the linked issue for details.
We only need the ProcessManager lock while we are iterating through the Process map. We should not continue to hold it while sending on an unbuffered channel.
> Don't send on unbuffered channel while holding a lock

- pkg/process/process_manager.go
- pkg/process/process_test.go
ref: https://github.com/longhorn/longhorn/issues/8094
The original check limit the pattern of the engine binary path.
But there is no need to check the engine binary path.
Even the path is wrong, we catch the error and show the error message.
> refactor: remove engine binary path check

- pkg/process/command.go
- pkg/process/process.go
https://github.com/longhorn/longhorn/issues/8091
We don't know how to reproduce this issue. But this PR allows retrying the process kill after a timeout anyway
> Allow retrying killing a process when it get stucks in stopping state

- pkg/util/grpcutil.go
Issue Longhorn/longhorn#8455
Add BaseDelay to grpc.ConnectParams.Backoff.
> Fix that instance-manager is stuck at starting state

- .github/workflows/build.yml
https://github.com/longhorn/longhorn/issues/8039
> ci: remove installing make in building arm64 images

- app/cmd/start.go
- go.mod
- go.sum
- pkg/client/proxy_snapshot.go
- pkg/proxy/snapshot.go
- vendor/github.com/longhorn/go-iscsi-helper/LICENSE
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go
- vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go
- vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go
- vendor/github.com/longhorn/go-iscsi-helper/types/tgtadm_errors.go
- vendor/github.com/longhorn/go-iscsi-helper/types/types.go
- vendor/github.com/longhorn/go-iscsi-helper/util/process.go
- vendor/github.com/longhorn/go-iscsi-helper/util/util.go
- vendor/github.com/longhorn/longhorn-engine/pkg/controller/client/controller_client.go
- vendor/github.com/longhorn/longhorn-engine/pkg/util/fsfreeze.go
- vendor/modules.txt
longhorn/longhorn#2187
- Proxy the freezeFS field for SnapshotVolume through to the engine.
- Attempt to unfreeze all file systems on the root partitions of Longhorn volumes on startup.
Depends on:
- https://github.com/longhorn/types/pull/8
- https://github.com/longhorn/longhorn-engine/pull/1083
Need to fix imports before merging.
> Add fsFreeze field to VolumeSnapshot

- package/Dockerfile
> Dockerfile: verify the dependencies for the binaries

- package/Dockerfile
The instance-manager pod for V2 volume is being terminated due to a failed liveness probe in https://github.com/longhorn/longhorn-manager/blob/master/controller/instance_manager_controller.go#L1314-L1315.
```
processProbe := "[ $(ps aux | grep 'spdk_tgt' | grep -v 'grep' | grep -v 'tee' | wc -l) != 0 ]"
livenessProbes = append(livenessProbes, processProbe)
```
This failure is caused by the removal of the ps utility (procps package) in the recent BCI 15.5 and 15.6 images.
Longhorn 8807
Issue #
> Dockerfile: add procps package for missing ps utility

- app/cmd/start.go
- go.mod
- go.sum
- package/Dockerfile
- pkg/api/instance.go
- pkg/client/instance.go
- pkg/instance/instance.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/util/dmsetup.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/api/types.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/client/client.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/disk.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/types.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/util.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/types/types.go
- vendor/modules.txt
> feat(upgrade): support v2 volume upgrade

- package/Dockerfile
Issue Longhorn/longhorn#9004
Disable the debug mode first. The issue doesn't always happen on all arm64 platforms and needs further investigation.
> fix(dockerfile): fix spdk_tgt hang and exit on arm64 platform after enabling debug mode

- pkg/proxy/snapshot.go
Handling snapshot timestamp for its creation time, if a snapshot has been created before the introduction of the new attribute SnapshotTimestamp, do fallback over ther old one CreationTime. This fix the commit 5af4f97.
Issue #9045
> fix(snapshot): time fallback over creation time

- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-engine/pkg/replica/backup.go
- vendor/modules.txt
ref: https://github.com/longhorn/longhorn/issues/9168
To prevent race conditions where some goroutines might update the status to 'In Progress' after the backup has already completed or failed, we should skip updating the status in such cases.
> fix: skip updating backup status when it is completed or failed

- pkg/disk/disk.go
- pkg/instance/instance.go
- pkg/proxy/proxy.go
longhorn/longhorn#9438
Explanation https://github.com/longhorn/longhorn/issues/9438#issuecomment-2347381660
> fix(cpu): high CPU usage of instance-manager pod caused by for tight loops

- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-engine/pkg/replica/replica.go
- vendor/modules.txt
> vendor: update dependencies

- go.mod
- go.sum
- pkg/client/instance.go
- pkg/instance/instance.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/client/client.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go
- vendor/modules.txt
Issue longhorn/longhorn#8430
Include snapshot disk info in the proxy.ReplicaList response.
`None`
`None`
> feat(auto-salvage): v2 support

- pkg/client/instance.go
- pkg/instance/log.go
Issue https://github.com/longhorn/longhorn/issues/6702
Add a handler for RPC call to set log level.
> fix(logging): handle RPC call to set V1 log level

- pkg/instance/log.go
Issue https://github.com/longhorn/longhorn/issues/6702
Separate the setting of instance-manager log level from that for v2 data engine (spdk_tgt).
> fix(logging): separate methods for internal and SPDK logging setting

- go.mod
- go.sum
- vendor/modules.txt
Issue longhorn/longhorn#9898
**After**
```
c3y1huang/research:545-lh-im (suse linux enterprise server 15.5)
================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
usr/local/bin/grpc_health_probe (gobinary)
==========================================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                       Title                       │
├──────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2024-45338 │ …
```
> chore(cve): update vendor

- package/Dockerfile
Issue https://github.com/longhorn/longhorn/issues/9922
Update `package/Dockerfile` to have `go-spdk-helper` updated with lvol detach functionality.
> chore(Dockerfile): update go-spdk-helper version

- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/backing_image.go
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/util/http_handler.go
- vendor/modules.txt
ref: https://github.com/longhorn/longhorn/issues/9876
skip writing zero when dumping data to backing image lvol
update the spdk engine go mod in this repo
> fix: skip writing zero when dumping data to backing image lvol

- .github/workflows/build.yml
- .github/workflows/scripts/build.sh
- package/Dockerfile
- scripts/package
Issue Longhorn/longhorn#10208
- move deps build codes to longhorn/dep-versions
- update workflows/build.yml
> chore(build): move deps build codes to longhorn/dep-versions

- Dockerfile.dapper
- package/Dockerfile
Issue longhorn/longhorn#10573
- chore(Dockerfile): revert registry.suse.com/bci/bci-base to 15.6
- chore(Dockerfile): use latest golangci-lint
- chore(Dockerfile): retry zypper commands if they are failed
> chore(Dockerfile): revert registry.suse.com/bci/bci-base to 15.6 and use latest golangci-lint

- Dockerfile.dapper
- package/Dockerfile
1. No need to snappy repo for the build container
2. No need to printout the build script
3. Need to verify gpg key when installing package
longhorn/longhorn#9456
> fix: remove unnecessary commands and add gpg key verification back

- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-spdk-engine/pkg/spdk/replica.go
- vendor/modules.txt
> chore(vendor): update dependencies

- package/Dockerfile
Issue #
SPDK ublk needs liburing2.
- amd64 liburing-devel is already liburing2.
- arm64 needs to install liburing2-devel explicitly.
ref: https://github.com/spdk/spdk/issues/3282
> chore(Docker): use liburing2-devel for SPDK ublk

- package/Dockerfile
We already specify the flag when building SPDK here https://github.com/longhorn/dep-versions/blob/d6a5694e59025d13a32bc2d86fe02d6ccfcb9ac6/scripts/build-spdk.sh#L42
longhorn/longhorn#10768
> fix: no need to manually install liburing

- go.mod
- go.sum
- vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
- vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go
- vendor/modules.txt
Issue https://github.com/longhorn/longhorn/issues/10799
Updated the version of go-spdk-helper and longhorn-spdk-engine with the new APIs for delta snapshot rebuilding
> chore(deps): update go-spdk-helper and longhorn-spdk-engine version

- pkg/client/proxy_replica.go
- pkg/client/proxy_types.go
- pkg/proxy/proxy.go
- pkg/proxy/replica.go
Issue https://github.com/longhorn/longhorn/issues/10770
- Adds a new `ReplicaRebuildingQosSet()` gRPC method to the `ProxyEngineService`
- Implements logic in `V2DataEngineProxyOps` to apply QoS settings to all WO replicas
- Only WO (Write-Only) mode replicas are targeted for QoS
> feat(proxy): implement ReplicaRebuildingQosSet for SPDK replica 

- main.go
- pkg/util/log.go
Issue Longhorn/longhorn#11596
Currently, the log output from Longhorn components uses the default logrus timestamp format, which typically provides only second- or millisecond-level precision.
For debugging and performance analysis, especially when investigating I/O latency and replica rebuilding, it would be helpful to increase timestamp precision to nanoseconds.
> feat: improve logging precision to nanoseconds
